#!/usr/bin/env bash

set -e

GIT_ROOT="$(git rev-parse --show-toplevel)"

mapfile -d "" -t FILES < <(
    git diff --cached --name-only --diff-filter=d -z
)

if [[ ${#FILES[@]} -ne 0 ]] && ! (git status --porcelain | grep -Eq "^([^? ][^? ])"); then
    "$GIT_ROOT/prettify.sh" "${FILES[@]}"
    git add "${FILES[@]}"
else
    echo "Found partially added file. Skipping prettify."
fi

"$GIT_ROOT/lint.sh"
