"""
This type stub file was generated by pyright.
"""

from pystache.init import Renderer, TemplateSpec, parse, render

"""
TODO: add a docstring.

"""
__all__ = ['parse', 'render', 'Renderer', 'TemplateSpec']
__version__ = ...
