#!/usr/bin/env bash

set -eu

if [[ -z ${TIMCOL_HOME-} ]]; then
    echo "FATAL: Provide data directory with \$TIMCOL_HOME"
    exit 1
fi

function get_script_dir {
    (
        local CUR="${BASH_SOURCE[0]}"
        while [[ -L $CUR ]]; do
            cd "$(dirname "$CUR")"
            cd "$(pwd -P)"
            CUR="$(readlink "$CUR")"
        done
        CUR="$(realpath "$CUR")"

        ( cd "$(dirname "$CUR")"; pwd -P )
    )

}

SCRIPT_DIR="$(get_script_dir)"

export LEDGER_FILE="$TIMCOL_HOME/ledger.dat"

function usage {
    echo "USAGE: $0 <command>"
    echo
    echo "COMMANDS"
    echo "  shell"
    echo "  start ACCOUNT TASK_DESCRIPTION"
    echo "  stop"
    echo "  edit"
    echo "  register"
    echo "  csv"
    echo "  json"
}

function last_directive {
    if [[ -f $LEDGER_FILE ]]; then
        printf "%s" "$(grep -o "^[ioO]" "$LEDGER_FILE" | tail -n 1)"
    fi
}

function get_timestamp {
    date +"%Y/%m/%d %I:%M:%S %p"
}

function maybe_update_hardstatus {
    if [[ ${TIMCOL_UPDATE_HARDSTATUS-} = yes &&
            -n $TIMCOL_SHELL_HELPER_PID ]] &&
            ! kill -SIGUSR1 "$TIMCOL_SHELL_HELPER_PID"; then
        echo "WARNING: Could not send update signal to shell helper."
    fi
}

case ${1-} in

    register | reg)
        if [[ ! -f $LEDGER_FILE ]]; then
            echo "NOTICE: No ledger file found."
            exit 0
        elif [[ $(last_directive) == "i" ]]; then
            echo "NOTICE: Task is pending"
        fi

        python3 "$SCRIPT_DIR/print_log" register "${@:2}" < "$LEDGER_FILE"
        ;;

    csv | json)
        if [[ ! -f $LEDGER_FILE ]]; then
            echo "NOTICE: No ledger file found."
            exit 0
        fi

        python3 "$SCRIPT_DIR/print_log" "$1" "${@:2}" < "$LEDGER_FILE"
        ;;

    stop)
        if [[ $(last_directive) != "i" ]]; then
            echo "FATAL: No task is pending."
            exit 1
        fi

        echo "o $(get_timestamp)" >> "$TIMCOL_HOME/ledger.dat"

        maybe_update_hardstatus
        ;;

    start)
        if [[ $(last_directive) == "i" ]]; then
            echo "FATAL: Task is pending."
            exit 1
        elif [[ $# -ne 3 || -z $2 || -z $3 ]]; then
            usage
            exit 1
        elif ! grep -q "^account $2\$" "$LEDGER_FILE"; then
            echo "FATAL: Unknown account $2"
            exit 1
        fi

        echo "i $(get_timestamp) $2  $3" >> "$LEDGER_FILE"

        maybe_update_hardstatus
        ;;

    shell)
        if [[ ${TIMCOL_SHELL-} = yes ]]; then
            echo "FATAL: You're already in the timcol shell."
            exit 1
        fi

        (
            export PATH="$SCRIPT_DIR/shell-bin:$PATH"
            export TIMCOL_REPO="$SCRIPT_DIR/.."
            export TIMCOL_HOME="${TIMCOL_HOME-$1}"
            export TIMCOL_SHELL=yes
            export TIMCOL_UPDATE_HARDSTATUS=yes
            screen -c "$SCRIPT_DIR/screenrc"
        )
        ;;

    edit)
        $EDITOR "$LEDGER_FILE"
        maybe_update_hardstatus
        ;;

    *)
        usage
        exit 1
        ;;

esac
